//! Walk-forward cross-validation with DSR / PSR / PBO truth-gate.
//!
//! Bailey & Lopez de Prado 2014 — Deflated Sharpe Ratio.

use std::ops::Range;
use std::f64::consts::PI;

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/// A single OHLCV bar (all prices in the same unit, e.g. USD).
#[derive(Debug, Clone, Copy)]
pub struct Bar {
    pub ts: i64,
    pub open: f64,
    pub high: f64,
    pub low: f64,
    pub close: f64,
    pub volume: f64,
}

/// Per-trade result used for WF statistics.
#[derive(Debug, Clone, Copy)]
pub struct TradeResult {
    /// P&L in return-space (e.g. 0.02 = +2%).
    pub ret: f64,
}

#[derive(Debug, Clone)]
pub struct FoldResult {
    pub fold_id: u32,
    pub n_trades: usize,
    pub sharpe: f64,
    pub sortino: f64,
    pub max_drawdown: f64,
    pub hit_rate: f64,
}

#[derive(Debug, Clone)]
pub struct WfReport {
    pub folds: Vec<FoldResult>,
    /// Deflated Sharpe Ratio (Bailey & Lopez de Prado 2014).
    pub dsr: f64,
    /// Probabilistic Sharpe p-value.
    pub psr_p_value: f64,
    /// Probability of Backtest Overfitting (combinatorial).
    pub pbo: f64,
    pub verdict: Verdict,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Verdict {
    Robust,
    Fragile,
    Overfit,
}

// ---------------------------------------------------------------------------
// WalkForward
// ---------------------------------------------------------------------------

pub struct WalkForward {
    pub folds: u32,
    pub train_ratio: f32,
    pub min_train_bars: u32,
}

impl WalkForward {
    pub fn new(folds: u32) -> Self {
        Self {
            folds,
            train_ratio: 0.7,
            min_train_bars: 50,
        }
    }

    /// Run WF over bars generated by `make_bars(ts_range)`.
    ///
    /// `strategy` receives a training slice and is expected to return trades.
    pub fn run<F>(&self, ts_range: Range<i64>, strategy: F) -> WfReport
    where
        F: Fn(&[Bar]) -> Vec<TradeResult>,
    {
        // Build synthetic bars spanning ts_range at 1-unit intervals.
        let total_len = (ts_range.end - ts_range.start).max(0) as usize;
        let bars: Vec<Bar> = (0..total_len)
            .map(|i| Bar {
                ts: ts_range.start + i as i64,
                open: 100.0,
                high: 100.0,
                low: 100.0,
                close: 100.0,
                volume: 1.0,
            })
            .collect();

        let n = bars.len();
        let fold_size = (n as f32 / self.folds as f32) as usize;

        let mut fold_results: Vec<FoldResult> = Vec::with_capacity(self.folds as usize);
        // Collect all IS sharpes for PBO.
        let mut is_sharpes: Vec<f64> = Vec::new();
        let mut oos_sharpes: Vec<f64> = Vec::new();

        for fold_id in 0..self.folds {
            let start = (fold_id as usize) * fold_size;
            let end = if fold_id == self.folds - 1 { n } else { (fold_id as usize + 1) * fold_size };
            if end <= start { continue; }
            let fold_bars = &bars[start..end];
            let train_end = (fold_bars.len() as f32 * self.train_ratio) as usize;
            if train_end < self.min_train_bars as usize { continue; }

            let train = &fold_bars[..train_end];
            let test  = &fold_bars[train_end..];

            let is_trades = strategy(train);
            let oos_trades = strategy(test);

            let is_sharpe = compute_sharpe(&is_trades);
            let oos_sharpe = compute_sharpe(&oos_trades);
            is_sharpes.push(is_sharpe);
            oos_sharpes.push(oos_sharpe);

            fold_results.push(FoldResult {
                fold_id,
                n_trades: oos_trades.len(),
                sharpe: oos_sharpe,
                sortino: compute_sortino(&oos_trades),
                max_drawdown: compute_max_drawdown(&oos_trades),
                hit_rate: compute_hit_rate(&oos_trades),
            });
        }

        // Compute DSR from combined OOS sharpe + IS distribution.
        let oos_sr = mean_f64(&oos_sharpes);
        let n_obs = n as f64;
        let skew = skewness(&oos_sharpes);
        let kurt = kurtosis(&oos_sharpes);
        let n_trials = self.folds as usize;

        let dsr = deflated_sharpe_ratio(oos_sr, n_obs, skew, kurt, n_trials);
        let psr_p_value = probabilistic_sharpe_p(oos_sr, n_obs, skew, kurt, 0.0);
        let pbo = prob_backtest_overfitting(&is_sharpes, &oos_sharpes);

        let avg_hit_rate = fold_results.iter().map(|f| f.hit_rate).sum::<f64>()
            / fold_results.len().max(1) as f64;

        let verdict = if dsr > 0.95 && pbo < 0.5 && avg_hit_rate > 0.55 {
            Verdict::Robust
        } else if pbo >= 0.5 {
            Verdict::Overfit
        } else {
            Verdict::Fragile
        };

        WfReport {
            folds: fold_results,
            dsr,
            psr_p_value,
            pbo,
            verdict,
        }
    }
}

// ---------------------------------------------------------------------------
// Statistics helpers
// ---------------------------------------------------------------------------

fn mean_f64(xs: &[f64]) -> f64 {
    if xs.is_empty() { return 0.0; }
    xs.iter().sum::<f64>() / xs.len() as f64
}

fn variance_f64(xs: &[f64]) -> f64 {
    if xs.len() < 2 { return 0.0; }
    let m = mean_f64(xs);
    xs.iter().map(|x| (x - m).powi(2)).sum::<f64>() / (xs.len() - 1) as f64
}

fn std_f64(xs: &[f64]) -> f64 { variance_f64(xs).sqrt() }

fn skewness(xs: &[f64]) -> f64 {
    if xs.len() < 3 { return 0.0; }
    let m = mean_f64(xs);
    let s = std_f64(xs);
    if s == 0.0 { return 0.0; }
    let n = xs.len() as f64;
    xs.iter().map(|x| ((x - m) / s).powi(3)).sum::<f64>() / n
}

fn kurtosis(xs: &[f64]) -> f64 {
    if xs.len() < 4 { return 3.0; }
    let m = mean_f64(xs);
    let s = std_f64(xs);
    if s == 0.0 { return 3.0; }
    let n = xs.len() as f64;
    xs.iter().map(|x| ((x - m) / s).powi(4)).sum::<f64>() / n
}

fn compute_sharpe(trades: &[TradeResult]) -> f64 {
    if trades.len() < 2 { return 0.0; }
    let rets: Vec<f64> = trades.iter().map(|t| t.ret).collect();
    let m = mean_f64(&rets);
    let s = std_f64(&rets);
    if s == 0.0 { return 0.0; }
    m / s * (252.0f64).sqrt()
}

fn compute_sortino(trades: &[TradeResult]) -> f64 {
    if trades.len() < 2 { return 0.0; }
    let rets: Vec<f64> = trades.iter().map(|t| t.ret).collect();
    let m = mean_f64(&rets);
    let neg: Vec<f64> = rets.iter().filter(|&&r| r < 0.0).map(|&r| r * r).collect();
    if neg.is_empty() { return f64::INFINITY; }
    let downside = (neg.iter().sum::<f64>() / neg.len() as f64).sqrt();
    if downside == 0.0 { return f64::INFINITY; }
    m / downside * (252.0f64).sqrt()
}

fn compute_max_drawdown(trades: &[TradeResult]) -> f64 {
    let mut peak = 0.0_f64;
    let mut dd = 0.0_f64;
    let mut cum = 0.0_f64;
    for t in trades {
        cum += t.ret;
        if cum > peak { peak = cum; }
        let d = peak - cum;
        if d > dd { dd = d; }
    }
    dd
}

fn compute_hit_rate(trades: &[TradeResult]) -> f64 {
    if trades.is_empty() { return 0.0; }
    let wins = trades.iter().filter(|t| t.ret > 0.0).count();
    wins as f64 / trades.len() as f64
}

// ---------------------------------------------------------------------------
// Bailey & Lopez de Prado 2014 — DSR
//
// DSR = Phi( (SR - E[SR_max]) * sqrt(T-1) / sqrt(1 - skew*SR + (kurt-1)/4 * SR^2) )
// E[SR_max] ≈ (1-γ)*Φ^{-1}(1-1/N) + γ*Φ^{-1}(1-1/(Ne))
// γ = Euler-Mascheroni ≈ 0.5772
// ---------------------------------------------------------------------------

const EULER_MASCHERONI: f64 = 0.5772156649015328;

/// Gaussian CDF (Abramowitz & Stegun 26.2.17).
pub fn norm_cdf(x: f64) -> f64 {
    0.5 * erfc(-x / std::f64::consts::SQRT_2)
}

/// Complementary error function (rational approx).
fn erfc(x: f64) -> f64 {
    // Horner-form rational approximation, max error ~1.5e-7
    let t = 1.0 / (1.0 + 0.3275911 * x.abs());
    let poly = t * (0.254829592
        + t * (-0.284496736
            + t * (1.421413741 + t * (-1.453152027 + t * 1.061405429))));
    let approx = poly * (-x * x).exp();
    if x >= 0.0 { approx } else { 2.0 - approx }
}

/// Inverse normal CDF (rational approx, Beasley-Springer-Moro).
pub fn norm_ppf(p: f64) -> f64 {
    const A: [f64; 4] = [2.515517, 0.802853, 0.010328, 0.0];
    const B: [f64; 3] = [1.432788, 0.189269, 0.001308];
    let p = p.clamp(1e-15, 1.0 - 1e-15);
    let sign = if p < 0.5 { -1.0 } else { 1.0 };
    let q = if p < 0.5 { p } else { 1.0 - p };
    let t = (-2.0 * q.ln()).sqrt();
    let num = A[0] + t * (A[1] + t * (A[2] + t * A[3]));
    let den = 1.0 + t * (B[0] + t * (B[1] + t * B[2]));
    sign * (t - num / den)
}

/// Expected maximum Sharpe over `n_trials` independent trials.
fn e_sr_max(n_trials: usize) -> f64 {
    let n = n_trials.max(2) as f64;
    let g = EULER_MASCHERONI;
    (1.0 - g) * norm_ppf(1.0 - 1.0 / n) + g * norm_ppf(1.0 - 1.0 / (n * std::f64::consts::E))
}

/// DSR (Bailey & Lopez de Prado 2014).
///
/// sr     : observed OOS Sharpe
/// t_obs  : number of observations
/// skew   : return skewness
/// kurt   : return excess kurtosis (so 0 = normal)
/// n_trials: number of strategies tested (for E[SR_max])
pub fn deflated_sharpe_ratio(sr: f64, t_obs: f64, skew: f64, kurt: f64, n_trials: usize) -> f64 {
    if t_obs < 2.0 { return 0.0; }
    let sr_star = e_sr_max(n_trials);
    // Denominator: sqrt(1 - skew*SR + (kurt-1)/4 * SR^2)
    let denom_sq = 1.0 - skew * sr + (kurt - 1.0) / 4.0 * sr * sr;
    if denom_sq <= 0.0 { return 0.0; }
    let z = (sr - sr_star) * (t_obs - 1.0).sqrt() / denom_sq.sqrt();
    norm_cdf(z)
}

/// Probabilistic Sharpe p-value (prob that SR > sr_benchmark).
pub fn probabilistic_sharpe_p(sr: f64, t_obs: f64, skew: f64, kurt: f64, sr_bench: f64) -> f64 {
    if t_obs < 2.0 { return 0.5; }
    let denom_sq = (1.0 - skew * sr + (kurt - 1.0) / 4.0 * sr * sr) / (t_obs - 1.0);
    if denom_sq <= 0.0 { return 1.0; }
    let z = (sr - sr_bench) / denom_sq.sqrt();
    norm_cdf(z)
}

/// Simple Probability of Backtest Overfitting: fraction of folds where
/// OOS rank < IS rank (deflated by median).
pub fn prob_backtest_overfitting(is_sharpes: &[f64], oos_sharpes: &[f64]) -> f64 {
    let n = is_sharpes.len().min(oos_sharpes.len());
    if n == 0 { return 0.5; }
    // Rank IS sharpes.
    let mut is_idx: Vec<usize> = (0..n).collect();
    is_idx.sort_by(|&a, &b| is_sharpes[b].partial_cmp(&is_sharpes[a]).unwrap());
    let median_oos = {
        let mut sorted: Vec<f64> = oos_sharpes[..n].to_vec();
        sorted.sort_by(|a, b| a.partial_cmp(b).unwrap());
        sorted[n / 2]
    };

    // Fraction of top-IS folds where OOS < median.
    let top_half = n / 2;
    let overfit = is_idx[..top_half.max(1)]
        .iter()
        .filter(|&&i| oos_sharpes[i] < median_oos)
        .count();
    overfit as f64 / top_half.max(1) as f64
}
