//! # synapse-compliance
//!
//! Compliance export with PII masking for synapse-memory. Produces GDPR/DSGVO-
//! ready exports of memories with sensitive data redacted.
//!
//! ## PII patterns detected
//!
//! - Email addresses
//! - Phone numbers (DE + international)
//! - IBAN
//! - Credit card numbers
//! - German tax IDs (Steuer-ID)
//! - German passport numbers
//! - IP addresses (IPv4 + IPv6)
//! - Dates of birth
//! - Street addresses (German format)
//!
//! ## Export formats
//!
//! - JSON (structured, machine-readable)
//! - CSV (tabular, for auditors)
//! - Markdown (human-readable report)
//!
//! ## Safety
//!
//! - All PII is replaced with `[REDACTED:type]` tokens.
//! - Original data is never written to export.
//! - Reversible only with a separate mapping file (not generated by default).

use anyhow::Result;
use chrono::Utc;
use regex::Regex;
use rusqlite::Connection;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use thiserror::Error;

#[derive(Debug, Error)]
pub enum ComplianceError {
    #[error("sqlite: {0}")]
    Sqlite(#[from] rusqlite::Error),
    #[error("regex: {0}")]
    Regex(String),
    #[error("export: {0}")]
    Export(String),
}

/// PII type classification.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PiiType {
    Email,
    Phone,
    Iban,
    CreditCard,
    TaxId,
    Passport,
    IpAddress,
    DateOfBirth,
    StreetAddress,
}

impl PiiType {
    pub fn as_str(&self) -> &str {
        match self {
            PiiType::Email => "email",
            PiiType::Phone => "phone",
            PiiType::Iban => "iban",
            PiiType::CreditCard => "credit_card",
            PiiType::TaxId => "tax_id",
            PiiType::Passport => "passport",
            PiiType::IpAddress => "ip",
            PiiType::DateOfBirth => "dob",
            PiiType::StreetAddress => "address",
        }
    }
}

/// A PII detection rule.
pub struct PiiRule {
    pub pii_type: PiiType,
    pub pattern: Regex,
}

/// All PII rules. Compiled once, reused.
pub struct PiiMasker {
    rules: Vec<PiiRule>,
}

impl PiiMasker {
    pub fn new() -> Result<Self> {
        let rules =
            vec![
            PiiRule {
                pii_type: PiiType::Email,
                pattern: Regex::new(r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b")
                    .map_err(|e| ComplianceError::Regex(e.to_string()))?,
            },
            PiiRule {
                pii_type: PiiType::Iban,
                pattern: Regex::new(r"\b[A-Z]{2}\d{2}(?:\s?\d{2,4}){4,12}\b")
                    .map_err(|e| ComplianceError::Regex(e.to_string()))?,
            },
            PiiRule {
                pii_type: PiiType::Phone,
                pattern: Regex::new(r"(?:\+49|0)[\s\-/]?(?:\d[\s\-/]?){6,14}\d")
                    .map_err(|e| ComplianceError::Regex(e.to_string()))?,
            },
            PiiRule {
                pii_type: PiiType::CreditCard,
                pattern: Regex::new(r"\b(?:\d[ -]?){13,16}\b")
                    .map_err(|e| ComplianceError::Regex(e.to_string()))?,
            },
            PiiRule {
                pii_type: PiiType::TaxId,
                pattern: Regex::new(r"\b\d{2}\.?\d{3}\.?\d{3}\.?\d{3}\b")
                    .map_err(|e| ComplianceError::Regex(e.to_string()))?,
            },
            PiiRule {
                pii_type: PiiType::Passport,
                pattern: Regex::new(r"\b[A-Z]{2}\d{8}\b")
                    .map_err(|e| ComplianceError::Regex(e.to_string()))?,
            },
            PiiRule {
                pii_type: PiiType::IpAddress,
                pattern: Regex::new(
                    r"\b(?:(?:25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(?:25[0-5]|2[0-4]\d|[01]?\d\d?)\b",
                )
                .map_err(|e| ComplianceError::Regex(e.to_string()))?,
            },
            PiiRule {
                pii_type: PiiType::DateOfBirth,
                pattern: Regex::new(r"\b\d{1,2}\.\d{1,2}\.\d{2,4}\b")
                    .map_err(|e| ComplianceError::Regex(e.to_string()))?,
            },
            PiiRule {
                pii_type: PiiType::StreetAddress,
                pattern: Regex::new(r"\b[A-ZÄÖÜ][a-zäöüß]+(?:straße|weg|gasse|allee|platz)\s+\d+\b")
                    .map_err(|e| ComplianceError::Regex(e.to_string()))?,
            },
        ];
        Ok(Self { rules })
    }

    /// Mask all PII in `text`. Returns masked text + count per type.
    pub fn mask(&self, text: &str) -> (String, HashMap<PiiType, u32>) {
        let mut masked = text.to_string();
        let mut counts: HashMap<PiiType, u32> = HashMap::new();
        for rule in &self.rules {
            let placeholder = format!("[REDACTED:{}]", rule.pii_type.as_str());
            let count = rule.pattern.find_iter(&masked.clone()).count() as u32;
            if count > 0 {
                masked = rule
                    .pattern
                    .replace_all(&masked, placeholder.as_str())
                    .to_string();
                *counts.entry(rule.pii_type.clone()).or_insert(0) += count;
            }
        }
        (masked, counts)
    }

    /// Mask a single string, returning only the masked output.
    pub fn mask_str(&self, text: &str) -> String {
        self.mask(text).0
    }
}

impl Default for PiiMasker {
    fn default() -> Self {
        Self::new().expect("pii rules compile")
    }
}

/// A masked memory record ready for export.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExportRecord {
    pub doc_id: String,
    pub agent: String,
    pub ts: i64,
    pub content_masked: String,
    pub pii_counts: HashMap<String, u32>,
    pub source_uri: Option<String>,
}

/// Export options.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExportOptions {
    /// If true, include PII counts per record.
    pub include_pii_counts: bool,
    /// If true, include agent identity.
    pub include_agent: bool,
    /// If true, include source URIs.
    pub include_source: bool,
    /// Max records to export (0 = all).
    pub max_records: usize,
}

impl Default for ExportOptions {
    fn default() -> Self {
        Self {
            include_pii_counts: true,
            include_agent: true,
            include_source: false,
            max_records: 0,
        }
    }
}

/// Export memories from a synapse-memory DB with PII masked.
///
/// Reads from the `docs` table (standard synapse-memory schema). Returns
/// masked records ready for JSON/CSV/Markdown serialization.
pub fn export_memories(
    conn: &Connection,
    masker: &PiiMasker,
    opts: &ExportOptions,
) -> Result<Vec<ExportRecord>> {
    let limit_clause = if opts.max_records > 0 {
        format!("LIMIT {}", opts.max_records)
    } else {
        String::new()
    };
    let mut stmt = conn.prepare(&format!(
        "SELECT id, agent, ts, content, uri FROM docs ORDER BY ts ASC {limit_clause}"
    ))?;
    let mut rows = stmt.query([])?;
    let mut out = Vec::new();
    while let Some(row) = rows.next()? {
        let doc_id: String = row.get(0)?;
        let agent: String = row.get(1).unwrap_or_default();
        let ts: i64 = row.get(2).unwrap_or_default();
        let content: String = row.get(3).unwrap_or_default();
        let uri: Option<String> = row.get(4).ok();
        let (masked, counts) = masker.mask(&content);
        let pii_counts: HashMap<String, u32> = counts
            .into_iter()
            .map(|(k, v)| (k.as_str().to_string(), v))
            .collect();
        out.push(ExportRecord {
            doc_id,
            agent,
            ts,
            content_masked: masked,
            pii_counts: if opts.include_pii_counts {
                pii_counts
            } else {
                HashMap::new()
            },
            source_uri: if opts.include_source { uri } else { None },
        });
    }
    Ok(out)
}

/// Serialize export records as JSON.
pub fn to_json(records: &[ExportRecord]) -> Result<String> {
    serde_json::to_string_pretty(records).map_err(|e| ComplianceError::Export(e.to_string()).into())
}

/// Serialize export records as CSV.
pub fn to_csv(records: &[ExportRecord]) -> Result<String> {
    let mut wtr = csv_writer::Writer::new();
    wtr.write_row(&[
        "doc_id",
        "agent",
        "ts",
        "pii_types",
        "pii_total",
        "content_masked",
    ])
    .map_err(ComplianceError::Export)?;
    for r in records {
        let pii_types: Vec<&str> = r.pii_counts.keys().map(|s| s.as_str()).collect();
        let pii_total: u32 = r.pii_counts.values().sum();
        wtr.write_row(&[
            &r.doc_id,
            &r.agent,
            &r.ts.to_string(),
            &pii_types.join(","),
            &pii_total.to_string(),
            &r.content_masked,
        ])
        .map_err(ComplianceError::Export)?;
    }
    Ok(wtr.into_string())
}

/// Serialize export records as a Markdown report.
pub fn to_markdown(records: &[ExportRecord]) -> Result<String> {
    let mut md = String::new();
    md.push_str("# Synapse Memory Compliance Export\n\n");
    md.push_str(&format!("Generated: {}\n\n", Utc::now().to_rfc3339()));
    md.push_str(&format!("Total records: {}\n\n", records.len()));
    let total_pii: u32 = records
        .iter()
        .map(|r| r.pii_counts.values().sum::<u32>())
        .sum();
    md.push_str(&format!("Total PII detections: {total_pii}\n\n"));
    md.push_str("---\n\n");
    for r in records {
        md.push_str(&format!("## Record `{}`\n\n", r.doc_id));
        md.push_str(&format!("- Agent: {}\n", r.agent));
        md.push_str(&format!("- Timestamp: {}\n", r.ts));
        if !r.pii_counts.is_empty() {
            md.push_str("- PII detected:\n");
            for (t, c) in &r.pii_counts {
                md.push_str(&format!("  - {t}: {c}\n"));
            }
        }
        md.push_str("\n### Content (masked)\n\n```\n");
        md.push_str(&r.content_masked);
        md.push_str("\n```\n\n");
    }
    Ok(md)
}

/// Minimal CSV writer (no external dep).
mod csv_writer {
    pub struct Writer {
        buf: String,
    }
    impl Writer {
        pub fn new() -> Self {
            Self { buf: String::new() }
        }
        pub fn write_row(&mut self, fields: &[&str]) -> Result<(), String> {
            let escaped: Vec<String> = fields
                .iter()
                .map(|f| {
                    if f.contains(',') || f.contains('"') || f.contains('\n') {
                        format!("\"{}\"", f.replace('"', "\"\""))
                    } else {
                        f.to_string()
                    }
                })
                .collect();
            self.buf.push_str(&escaped.join(","));
            self.buf.push('\n');
            Ok(())
        }
        pub fn into_string(self) -> String {
            self.buf
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::NamedTempFile;

    fn fresh_conn() -> Connection {
        let f = NamedTempFile::new().unwrap().keep().unwrap().1;
        let conn = Connection::open(&f).unwrap();
        conn.execute_batch(
            "CREATE TABLE docs (
                id TEXT PRIMARY KEY,
                agent TEXT,
                ts INTEGER,
                content TEXT,
                uri TEXT
            );",
        )
        .unwrap();
        conn
    }

    fn insert_doc(
        conn: &Connection,
        id: &str,
        agent: &str,
        ts: i64,
        content: &str,
        uri: Option<&str>,
    ) {
        conn.execute(
            "INSERT INTO docs (id, agent, ts, content, uri) VALUES (?1, ?2, ?3, ?4, ?5)",
            rusqlite::params![id, agent, ts, content, uri],
        )
        .unwrap();
    }

    #[test]
    fn mask_email() {
        let m = PiiMasker::new().unwrap();
        let (masked, counts) = m.mask("Contact: alice@example.com");
        assert!(masked.contains("[REDACTED:email]"));
        assert!(!masked.contains("alice@example.com"));
        assert_eq!(counts.get(&PiiType::Email), Some(&1));
    }

    #[test]
    fn mask_phone_de() {
        let m = PiiMasker::new().unwrap();
        let (masked, counts) = m.mask("Call +49 30 12345678");
        assert!(masked.contains("[REDACTED:phone]"));
        assert_eq!(counts.get(&PiiType::Phone), Some(&1));
    }

    #[test]
    fn mask_iban() {
        let m = PiiMasker::new().unwrap();
        let (masked, counts) = m.mask("IBAN: DE89 3704 0044 0532 0130 00");
        assert!(masked.contains("[REDACTED:iban]"));
        assert_eq!(counts.get(&PiiType::Iban), Some(&1));
    }

    #[test]
    fn mask_tax_id() {
        let m = PiiMasker::new().unwrap();
        let (masked, counts) = m.mask("Steuer-ID: 12.345.678.901");
        assert!(masked.contains("[REDACTED:tax_id]"));
        assert_eq!(counts.get(&PiiType::TaxId), Some(&1));
    }

    #[test]
    fn mask_ipv4() {
        let m = PiiMasker::new().unwrap();
        let (masked, counts) = m.mask("Server at 192.168.1.100");
        assert!(masked.contains("[REDACTED:ip]"));
        assert_eq!(counts.get(&PiiType::IpAddress), Some(&1));
    }

    #[test]
    fn mask_multiple_pii_types() {
        let m = PiiMasker::new().unwrap();
        let text = "Email: alice@example.com, Phone: +49 30 12345678, IP: 10.0.0.1";
        let (masked, counts) = m.mask(text);
        assert!(masked.contains("[REDACTED:email]"));
        assert!(masked.contains("[REDACTED:phone]"));
        assert!(masked.contains("[REDACTED:ip]"));
        assert_eq!(counts.len(), 3);
    }

    #[test]
    fn mask_preserves_non_pii() {
        let m = PiiMasker::new().unwrap();
        let (masked, _) = m.mask("Hello world, this is a test.");
        assert_eq!(masked, "Hello world, this is a test.");
    }

    #[test]
    fn export_memories_masks_all() {
        let conn = fresh_conn();
        insert_doc(
            &conn,
            "doc-1",
            "claude",
            1000,
            "Email: alice@example.com and IP 1.2.3.4",
            Some("file:///foo.rs"),
        );
        let m = PiiMasker::new().unwrap();
        let records = export_memories(&conn, &m, &ExportOptions::default()).unwrap();
        assert_eq!(records.len(), 1);
        assert!(records[0].content_masked.contains("[REDACTED:email]"));
        assert!(records[0].content_masked.contains("[REDACTED:ip]"));
        assert!(!records[0].content_masked.contains("alice@example.com"));
    }

    #[test]
    fn export_respects_max_records() {
        let conn = fresh_conn();
        for i in 0..10 {
            insert_doc(&conn, &format!("doc-{i}"), "claude", i, "no pii", None);
        }
        let m = PiiMasker::new().unwrap();
        let opts = ExportOptions {
            max_records: 3,
            ..Default::default()
        };
        let records = export_memories(&conn, &m, &opts).unwrap();
        assert_eq!(records.len(), 3);
    }

    #[test]
    fn export_excludes_source_when_disabled() {
        let conn = fresh_conn();
        insert_doc(
            &conn,
            "doc-1",
            "claude",
            1000,
            "content",
            Some("file:///secret.rs"),
        );
        let m = PiiMasker::new().unwrap();
        let opts = ExportOptions {
            include_source: false,
            ..Default::default()
        };
        let records = export_memories(&conn, &m, &opts).unwrap();
        assert!(records[0].source_uri.is_none());
    }

    #[test]
    fn to_json_produces_valid_json() {
        let records = vec![ExportRecord {
            doc_id: "doc-1".into(),
            agent: "claude".into(),
            ts: 1000,
            content_masked: "masked".into(),
            pii_counts: HashMap::from([("email".into(), 1)]),
            source_uri: None,
        }];
        let json = to_json(&records).unwrap();
        let parsed: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed[0]["doc_id"], "doc-1");
    }

    #[test]
    fn to_csv_produces_header_and_rows() {
        let records = vec![ExportRecord {
            doc_id: "doc-1".into(),
            agent: "claude".into(),
            ts: 1000,
            content_masked: "masked".into(),
            pii_counts: HashMap::from([("email".into(), 1)]),
            source_uri: None,
        }];
        let csv = to_csv(&records).unwrap();
        assert!(csv.contains("doc_id,agent,ts"));
        assert!(csv.contains("doc-1"));
    }

    #[test]
    fn to_markdown_includes_summary() {
        let records = vec![ExportRecord {
            doc_id: "doc-1".into(),
            agent: "claude".into(),
            ts: 1000,
            content_masked: "masked content".into(),
            pii_counts: HashMap::from([("email".into(), 2)]),
            source_uri: None,
        }];
        let md = to_markdown(&records).unwrap();
        assert!(md.contains("# Synapse Memory Compliance Export"));
        assert!(md.contains("Total records: 1"));
        assert!(md.contains("Total PII detections: 2"));
        assert!(md.contains("masked content"));
    }

    #[test]
    fn csv_escapes_commas_in_content() {
        let records = vec![ExportRecord {
            doc_id: "doc-1".into(),
            agent: "claude".into(),
            ts: 1000,
            content_masked: "has, comma".into(),
            pii_counts: HashMap::new(),
            source_uri: None,
        }];
        let csv = to_csv(&records).unwrap();
        assert!(csv.contains("\"has, comma\""));
    }
}
