/* Auto-generated by cbindgen. DO NOT EDIT. */
/* synapse-market C ABI — stable extern "C" surface */

#ifndef SYNAPSE_MARKET_H
#define SYNAPSE_MARKET_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/** Opaque handle to an open market database. */
typedef struct MarketHandle MarketHandle;

/**
 * Open (or create) a market database at `path`.
 * Returns NULL on failure.
 */
MarketHandle *smx_market_open(const char *path);

/**
 * Close and free a market handle. No-op on NULL.
 */
void smx_market_close(MarketHandle *handle);

/**
 * Ingest OHLCV rows for `ticker`.
 * `rows` is a packed f64 array: [ts, open, high, low, close, volume, ...], `n_rows` rows.
 * Returns 0 on success, -1 on error.
 */
int32_t smx_ingest_ohlcv(MarketHandle *handle,
                          const char *ticker,
                          const double *rows,
                          size_t n_rows);

/**
 * Query close prices for `ticker` in [start_ts, end_ts].
 * Writes up to `max_len` f64 values into `out_buf`.
 * Returns count written, or -1 on error.
 */
int64_t smx_series_range_close(MarketHandle *handle,
                                const char *ticker,
                                int64_t start_ts,
                                int64_t end_ts,
                                double *out_buf,
                                size_t max_len);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* SYNAPSE_MARKET_H */
